### PR TITLE
Specify unit test project

### PR DESCRIPTION
**Pull request by markWarr**

### CODE REVIEW

**Comment by Bhavesh-Patel** [comment]
Why does the test project need specifying explicitly?

`dotnet test` uses the solution file to find all projects and then identifies test projects and runs their tests.

**Comment by Bhavesh-Patel** [comment]
Just noticed the branch name, which indicates that this is an attempt to fix the unit tests hanging...also noticed that the CI pipeline for this PR had hanging tests too 😞 , which means it's not a direct fix.

**Comment by markWarr** [comment]
@Bhavesh-Patel Yes this was an attempt to fix the unit tests hanging. As you say it hasn't worked so I'll delete this pull request.

**Comment by markWarr** [comment]
Fix didn't work - unit tests are still intermittently hanging.

**Pull request closed without merging**
