### PR TITLE
Add terraform resources for key vault and access policy

### PR DESCRIPTION
**Pull request by Renny4Real**
This should add the resources we need to create an empty key vault and allow our app service to read from it.

### CODE REVIEW

**Comment by Renny4Real** [comment]
Not ready for review as this needs to be tested locally and possibly updated like what we've done in this other [PR](https://github.com/Newarkandsherwood/HousingRepairsSchedulingApi/pull/8), which contains changes from local terraform testing.

**Comment by Renny4Real** [comment]
Haven't been able to test this with terraform plan as I get an error with the sor code configuration env.tfvars variable when I try to run terraform plan locally. Getting this error: `Error: Missing newline after argument`.

**Review by jamiejordanmt — APPROVED** [review]

**Comment by jamiejordanmt** [comment]
[Create the Key Vault, Identity & Role terraform resources](https://trello.com/c/yn0cYiig/150-create-the-key-vault-identity-role-terraform-resources)

**Comment by Renny4Real** [comment]
[Create the Key Vault, Identity & Role terraform resources](https://trello.com/c/yn0cYiig/150-create-the-key-vault-identity-role-terraform-resources)

**Pull request merged**
